### ISSUE TITLE
Support php 8.1

### ISSUE THREAD

**Issue by mdsohelmia** [jobtech-dev/laravel-chunky#38]
[InvalidArgumentException]
  Package jobtech/laravel-chunky has requirements incompatible with your PHP
  version, PHP extensions and Composer version:
    - jobtech/laravel-chunky 1.4.1 requires php ^7.4 which does not match you
  r installed version 8.1.3.

**Comment by ilgala** [comment]
Hi @sohel1999 , sorry for the late answer. I'll update the package as soon as possible. Meanwhile if you want to open a PR to fix it on your own I'll be glad to check it!
